### ISSUE TITLE
python3 debugging code

### ISSUE THREAD

**Issue by NewbieOubie2017** [wobine/blackboard101#14]
I edited the code to get it to run with python3 but it still is not completely debugged...
this is what I get when it runs:
******* Public Key Generation *********
the private key (in base 10 format):
75263518707598184987916378021939673586055614731957507592904438851787542395619

the uncompressed public key (starts with '04' & is not the public address):
04 0.0 0.0

******* Signature Generation *********
r = 0.0
s = 0.0

******* Signature Verification *********>>
Traceback (most recent call last):
  File "CreateEllipticCurvesPart5TheMagicSigningAndVerifyingdebugged.py", line 63, in <module>
    xu2, yu2 = EccMultiply(xPublicKey,yPublicKey,(r*w)%N)
  File "CreateEllipticCurvesPart5TheMagicSigningAndVerifyingdebugged.py", line 39, in EccMultiply
    if Scalar == 0 or Scalar >= N: raise Exception("Invalid Scalar/Private Key")
Exception: Invalid Scalar/Private Key

Basically I just put in parentheses in the print commands.  Here is the new code. 

# Python 2.7.6 - Super simple Elliptic Curve Presentation. No imported libraries, wrappers, nothing. # For educational purposes only
# Below are the public specs for Bitcoin's curve - the secp256k1
Pcurve = 2**256 - 2**32 - 2**9 - 2**8 - 2**7 - 2**6 - 2**4 -1 # The proven prime
N=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 # Number of points in the field
Acurve = 0; Bcurve = 7 # This defines the curve. y^2 = x^3 + Acurve * x + Bcurve
Gx = 55066263022277343669578718895168534326250603453777594175500187360389116729240
Gy = 32670510020758816978083085130507043184471273380659243275938904335757337482424
GPoint = (Gx,Gy) # This is our generator point. Tillions of dif ones possible

#Individual Transaction/Personal Information
privKey = 75263518707598184987916378021939673586055614731957507592904438851787542395619 #replace with any private key
RandNum = 28695618543805844332113829720373285210420739438570883203839696518176414791234 #replace with a truly random number
HashOfThingToSign = 86032112319101611046176971828093669637772856272773459297323797145286374828050 # the hash of your message/transaction

def modinv(a,n=Pcurve): #Extended Euclidean Algorithm/'division' in elliptic curves
    lm, hm = 1,0
    low, high = a%n,n
    while low > 1:
        ratio = high/low
        nm, new = hm-lm*ratio, high-low*ratio
        lm, low, hm, high = nm, new, lm, low
    return lm % n

def ECadd(xp,yp,xq,yq): # Not true addition, invented for EC. It adds Point-P with Point-Q.
    m = ((yq-yp) * modinv(xq-xp,Pcurve)) % Pcurve
    xr = (m*m-xp-xq) % Pcurve
    yr = (m*(xp-xr)-yp) % Pcurve
    return (xr,yr)

def ECdouble(xp,yp): # EC point doubling,  invented for EC. It doubles Point-P.
    LamNumer = 3*xp*xp+Acurve
    LamDenom = 2*yp
    Lam = (LamNumer * modinv(LamDenom,Pcurve)) % Pcurve
    xr = (Lam*Lam-2*xp) % Pcurve
    yr = (Lam*(xp-xr)-yp) % Pcurve
    return (xr,yr)

def EccMultiply(xs,ys,Scalar): # Double & add. EC Multiplication, Not true multiplication
    if Scalar == 0 or Scalar >= N: raise Exception("Invalid Scalar/Private Key")
    ScalarBin = str(bin(Scalar))[2:]
    Qx,Qy=xs,ys
    for i in range (1, len(ScalarBin)): # This is invented EC multiplication.
        Qx,Qy=ECdouble(Qx,Qy); # print "DUB", Qx; print
        if ScalarBin[i] == "1":
            Qx,Qy=ECadd(Qx,Qy,xs,ys); # print "ADD", Qx; print
    return (Qx,Qy)

print()
print( "******* Public Key Generation *********")
xPublicKey, yPublicKey = EccMultiply(Gx,Gy,privKey)
print( "the private key (in base 10 format):"); print(privKey); print()
print("the uncompressed public key (starts with '04' & is not the public address):"); print("04", xPublicKey, yPublicKey)

print(); print("******* Signature Generation *********")
xRandSignPoint, yRandSignPoint = EccMultiply(Gx,Gy,RandNum)
r = xRandSignPoint % N
print("r =", r)
s = ((HashOfThingToSign + r*privKey)*(modinv(RandNum,N))) % N; print("s =", s)

print(); print("******* Signature Verification *********>>")
w = modinv(s,N)
xu1, yu1 = EccMultiply(Gx,Gy,(HashOfThingToSign * w)%N)
xu2, yu2 = EccMultiply(xPublicKey,yPublicKey,(r*w)%N)
x,y = ECadd(xu1,yu1,xu2,yu2)
print(r==x); print()

**Comment by molet01** [comment]
ratio = high/low must be an integer division, change it into  ratio = high // low

**Comment by riccardo123github** [comment]
This is the output I get:

******* Public Key Generation *********
the private key (in base 10 format):
75263518707598184987916378021939673586055614731957507592904438851787542395619

the uncompressed public key (starts with '04' & is not the public address):
04 61683183069034145073130731644405505880595088749069258798845189461983047171600 3858530736284730055676268774084424282127104290053135795900971267339186262624

******* Signature Generation *******
r = 87917229428110789366561422587307072970088695150214603900351294636804298290738
s = 64484809805191105156776226102374844389475739625477999177715914038772959217113

******* Signature Verification ********>>
False


...  if you watch here:

https://www.youtube.com/watch?v=U2bw_N6kQL8

at 2:56 also the uncompressed public key seems to be wrong ... even though all the parameters (Gx,Gy,randKey, Pcurve, N) are EXACTLY the same.

Any idea on why ?

**Comment by riccardo123github** [comment]
... I have also noticed the following "stuff" with Phyton3, if you change the private key with the following:

privKey = 0x095E09260673B23E228D76C32B4526607E3865810C1331EC9D20D97230ECDF4B

... you can go here:
https://www.bitaddress.org
... and select "Wallet details" after having randomly generated the key by moving your mouse. Insert the 64-characters long private key without the leading "0x", you will obtain the public key, uncompressed, compressed, utf-58 form and so on.


The script in phyton 3 provides the following output:

******* Public Key Generation *********
the private key (in base 10 format):
4236962402213128520172887130539802411719789190905435723796733663202824216395
the private key (in hex format):
0x95e09260673b23e228d76c32b4526607e3865810c1331ec9d20d97230ecdf4b
(NOTE: the leading "0" in the private key is not showed, it is skipped)

the uncompressed public key (starts with '04' & is not the public address):
04 58267326229385434195587303750215864706655459148209677094839092494020051103355 26377479543232341771191348012265337846753788405459789257004496248565921069783

X coordinate, public key in hex format:
0x80d22350576a8ecf5e32d9a7a8e6d1a526a099c836471b850061ffb2bd7a6e7b
The official Public Key - compressed:
03080d22350576a8ecf5e32d9a7a8e6d1a526a099c836471b850061ffb2bd7a6e7

Note that the compressed form of the public key, is completely different from the one in the internet site above, and for some unknown reason it also "looses" the last "b" character, which is not printed. This is the code I've copied somewhere else to print it out:

print("The official Public Key - compressed:") 
if (yPublicKey % 2 == 1): # If the Y value for the Public Key is odd.
    print("03"+str(hex(xPublicKey)[2:-1]).zfill(64))
else: # Or else, if the Y value is even.
    print("02"+str(hex(xPublicKey)[2:-1]).zfill(64))

The problem with cryptography, is that if things do not work understanding why is a real nightmare ...

**Comment by ricky-andre** [comment]
This version worked for me:

Pcurve = 2**256 - 2**32 - 2**9 - 2**8 - 2**7 - 2**6 - 2**4 -1 # The proven prime
Acurve = 0; Bcurve = 7 # These two defines the elliptic curve. y^2 = x^3 + Acurve * x + Bcurve
Gx = 55066263022277343669578718895168534326250603453777594175500187360389116729240
Gy = 32670510020758816978083085130507043184471273380659243275938904335757337482424
GPoint = (Gx,Gy) # Generator Point
N=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 # Number of points in the field
privKey = 75263518707598184987916378021939673586055614731957507592904438851787542395619

RandNum = 28695618543805844332113829720373285210420739438570883203839696518176414791234 #replace with a truly random number
HashOfThingToSign = 86032112319101611046176971828093669637772856272773459297323797145286374828050 # the hash of your message/transaction

def modinv(a,b=Pcurve): #Extended Euclidean Algorithm/'division' in elliptic curves
    lm, hm = 1,0
    low, high = a%b,b
    while low > 1:
        ratio = high//low
        nm, new = hm-lm*ratio, high-low*ratio
        lm, low, hm, high = nm, new, lm, low
    return lm % b

def ECAdd(a,b): # Point addition, invented for EC.
    LambdaAdd = ((b[1] - a[1]) * modinv(b[0] - a[0],Pcurve)) % Pcurve
    x = (LambdaAdd * LambdaAdd - a[0] - b[0]) % Pcurve
    y = (LambdaAdd * (a[0] - x) - a[1]) % Pcurve
    return (x,y)

def ECDouble(a): # Point Doubling, also invented for EC.
    LamdaDouble = ((3 * a[0] * a[0] + Acurve) * modinv((2 * a[1]), Pcurve)) % Pcurve
    x = (LamdaDouble * LamdaDouble - 2 * a[0]) % Pcurve
    y = (LamdaDouble * (a[0] - x) - a[1]) % Pcurve
    return (x,y)

def ECMultiply(GenPoint,privKeyHex): #Double & add. Not true multiplication
    if privKeyHex == 0 or privKeyHex >= N: raise Exception("Invalid Private Key")
    privKeyBin = str(bin(privKeyHex))[2:]
    Q=GenPoint
    for i in range (1, len(privKeyBin)):
        Q=ECDouble(Q);
        if privKeyBin[i] == "1":
            Q=ECAdd(Q,GenPoint);
    return (Q)

PublicKey = ECMultiply(GPoint,privKey)
print("Private Key:")
print (privKey)
print("\nPublic Key public key (uncompressed):")
print ("04", PublicKey)
print("\nPublic Key (compressed):")
if (PublicKey[1] % 2 == 1): # If the Y coordinate of the Public Key is odd.
    print("03"+str(hex(PublicKey[0])[2:]).zfill(64))
else: # If the Y coordinate is even.
    print("02"+str(hex(PublicKey[0])[2:]).zfill(64))

print("\n******* Signature Generation *******")
xRandSignPoint, yRandSignPoint = ECMultiply(GPoint,RandNum)
r = xRandSignPoint % N
print("r =", r)
s = ((HashOfThingToSign + r*privKey)*(modinv(RandNum,N))) % N
print("s =", s)


print("\n******* Signature Verification ********>>")
w = modinv(s,N)
x, y = ECAdd(ECMultiply(GPoint,(HashOfThingToSign * w) % N), ECMultiply(PublicKey,(r*w) % N))
print(r==x);

**Comment by ricky-andre** [comment]
You can also find the code here:
https://github.com/roheat/PublicKeyGeneration/

... even though you have to fix the following:
- as explained above ratio = high//low (double back slash)
- when printing the compressed version, the hex string needs to be cutted with [2:] (and NOT [2:-1])

and of course the print statements need to be modified.

**Comment by NewbieOubie2017** [comment]
Okay I made those changes and hopefully submitted it correctly.

**Comment by fassstturtle** [comment]
> This version worked for me:
> 
> Pcurve = 2**256 - 2**32 - 2**9 - 2**8 - 2**7 - 2**6 - 2**4 -1 # The proven prime
> Acurve = 0; Bcurve = 7 # These two defines the elliptic curve. y^2 = x^3 + Acurve * x + Bcurve
> Gx = 55066263022277343669578718895168534326250603453777594175500187360389116729240
> Gy = 32670510020758816978083085130507043184471273380659243275938904335757337482424
> GPoint = (Gx,Gy) # Generator Point
> N=0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 # Number of points in the field
> privKey = 75263518707598184987916378021939673586055614731957507592904438851787542395619
> 
> RandNum = 28695618543805844332113829720373285210420739438570883203839696518176414791234 #replace with a truly random number
> HashOfThingToSign = 86032112319101611046176971828093669637772856272773459297323797145286374828050 # the hash of your message/transaction
> 
> def modinv(a,b=Pcurve): #Extended Euclidean Algorithm/'division' in elliptic curves
> lm, hm = 1,0
> low, high = a%b,b
> while low > 1:
> ratio = high//low
> nm, new = hm-lm_ratio, high-low_ratio
> lm, low, hm, high = nm, new, lm, low
> return lm % b
> 
> def ECAdd(a,b): # Point addition, invented for EC.
> LambdaAdd = ((b[1] - a[1]) * modinv(b[0] - a[0],Pcurve)) % Pcurve
> x = (LambdaAdd * LambdaAdd - a[0] - b[0]) % Pcurve
> y = (LambdaAdd * (a[0] - x) - a[1]) % Pcurve
> return (x,y)
> 
> def ECDouble(a): # Point Doubling, also invented for EC.
> LamdaDouble = ((3 * a[0] * a[0] + Acurve) * modinv((2 * a[1]), Pcurve)) % Pcurve
> x = (LamdaDouble * LamdaDouble - 2 * a[0]) % Pcurve
> y = (LamdaDouble * (a[0] - x) - a[1]) % Pcurve
> return (x,y)
> 
> def ECMultiply(GenPoint,privKeyHex): #Double & add. Not true multiplication
> if privKeyHex == 0 or privKeyHex >= N: raise Exception("Invalid Private Key")
> privKeyBin = str(bin(privKeyHex))[2:]
> Q=GenPoint
> for i in range (1, len(privKeyBin)):
> Q=ECDouble(Q);
> if privKeyBin[i] == "1":
> Q=ECAdd(Q,GenPoint);
> return (Q)
> 
> PublicKey = ECMultiply(GPoint,privKey)
> print("Private Key:")
> print (privKey)
> print("\nPublic Key public key (uncompressed):")
> print ("04", PublicKey)
> print("\nPublic Key (compressed):")
> if (PublicKey[1] % 2 == 1): # If the Y coordinate of the Public Key is odd.
> print("03"+str(hex(PublicKey[0])[2:]).zfill(64))
> else: # If the Y coordinate is even.
> print("02"+str(hex(PublicKey[0])[2:]).zfill(64))
> 
> print("\n******* Signature Generation *****__") xRandSignPoint, yRandSignPoint = ECMultiply(GPoint,RandNum) r = xRandSignPoint % N print("r =", r) s = ((HashOfThingToSign + r_privKey)_(modinv(RandNum,N))) % N
> print("s =", s)
> 
> print("\n******* Signature Verification ********>>")
> w = modinv(s,N)
> x, y = ECAdd(ECMultiply(GPoint,(HashOfThingToSign * w) % N), ECMultiply(PublicKey,(r*w) % N))
> print(r==x);

Hi I'm quite new to python and could someone explain to me what functions do the [] brackets have with [0] and [1] next to some variables. If you remove them the code doesn't work anymore so they seem to have an important role, but I can't quite figure it out. They sure aren't displaying the 1st or 2nd character.

**Comment by gtmadureira** [comment]
https://github.com/gtmadureira/bitcoin_address-generator/blob/main/app_python/privkey_to_pubkey/secp256k1.py

# CODE FOR PYTHON 3:
```txt
# Super simple Elliptic Curve Presentation.
# For educational purposes only. Works in Python 3.
# Source: https://github.com/gtmadureira/blackboard101/blob/main/EllipticCurvesPart4-PrivateKeyToPublicKey.py

import random
import array
import hashlib
import os
import sys

# Checking the type of Operating System.
if sys.platform == "linux" or sys.platform == "linux2" or sys.platform == "darwin":
    def clear(): os.system('clear') # On Linux/OS X System
elif sys.platform == "win32":
    def clear(): os.system('cls') # On Windows System

clear()

# Maximum length of password needed.
# This can be changed to suit your password length.
MAX_LEN = 1024

# Declare arrays of the character that we need in out password.
# Represented as chars to enable easy string concatenation.
DIGITS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

LOCASE_CHARACTERS = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
					 'i', 'j', 'k', 'm', 'n', 'o', 'p', 'q',
					 'r', 's', 't', 'u', 'v', 'w', 'x', 'y',
					 'z']

UPCASE_CHARACTERS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
					 'I', 'J', 'K', 'M', 'N', 'O', 'p', 'Q',
					 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y',
					 'Z']

SYMBOLS = ['!', '"', '#', '$', '%', '&', "'", '(', ')', '*',
           '+', ',' , '-', '.', '/', ':', ';', '<', '=', '>',
           '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|',
           '}', '~', ' ']

# Combines all the character arrays above to form one array.
COMBINED_LIST = DIGITS + UPCASE_CHARACTERS + LOCASE_CHARACTERS + SYMBOLS

# Randomly select at least one character from each character set above.
rand_digit = random.choice(DIGITS)
rand_upper = random.choice(UPCASE_CHARACTERS)
rand_lower = random.choice(LOCASE_CHARACTERS)
rand_symbol = random.choice(SYMBOLS)

# Combine the character randomly selected above
# at this stage, the password contains only 4 characters but
# we want a 12-character password.
temp_pass = rand_digit + rand_upper + rand_lower + rand_symbol

# Now that we are sure we have at least one character from each
# set of characters, we fill the rest of
# the password length by selecting randomly from the combined
# list of character above.
for x in range(MAX_LEN - 4):
	temp_pass = temp_pass + random.choice(COMBINED_LIST)

	# Convert temporary password into array and shuffle to
	# prevent it from having a consistent pattern
	# where the beginning of the password is predictable.
	temp_pass_list = array.array('u', temp_pass)
	random.shuffle(temp_pass_list)

# Traverse the temporary password array and append the chars
# to form the password.
password = ""
for x in temp_pass_list:
		password = password + x

# Hashing password with SHA3-256 algorithm.
hash = hashlib.sha3_256()
hash.update(password.encode())

privKeyStr = "0x"+hash.hexdigest() # Random Private Key at hex_string.
privKey = int(privKeyStr, 16) # Random Private Key at hex_value.

# secp256k1 domain parameters.
Pcurve = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F # The proven prime.
Acurve = 0x0000000000000000000000000000000000000000000000000000000000000000 # These two defines the elliptic curve. y^2 = x^3 + int(Acurve) * x + int(Bcurve).
Bcurve = 0x0000000000000000000000000000000000000000000000000000000000000007
Gx = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
Gy = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
GPoint = (int(Gx),int(Gy)) # This is our generator point.
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 # Number of points in the field.

def modinv(a, b = int(Pcurve)): #Extended Euclidean Algorithm/'division' in elliptic curves.
    lm, hm = 1,0
    low, high = a%b,b
    while low > 1:
        ratio = high//low
        nm, new = hm-lm*ratio, high-low*ratio
        lm, low, hm, high = nm, new, lm, low
    return lm % b

def ECAdd(a,b): # Point Addition, invented for EC.
    LambdaAdd = ((b[1] - a[1]) * modinv(b[0] - a[0],int(Pcurve))) % int(Pcurve)
    x = (LambdaAdd * LambdaAdd - a[0] - b[0]) % int(Pcurve)
    y = (LambdaAdd * (a[0] - x) - a[1]) % int(Pcurve)
    return (x,y)

def ECDouble(a): # Point Doubling, invented for EC.
    LamdaDouble = ((3 * a[0] * a[0] + int(Acurve)) * modinv((2 * a[1]), int(Pcurve))) % int(Pcurve)
    x = (LamdaDouble * LamdaDouble - 2 * a[0]) % int(Pcurve)
    y = (LamdaDouble * (a[0] - x) - a[1]) % int(Pcurve)
    return (x,y)

def ECMultiply(GenPoint,privKeyHex): # Doubling & Addition. Not true multiplication.
    if privKeyHex == 0 or privKeyHex >= N: raise Exception("Invalid Private Key")
    privKeyBin = str(bin(privKeyHex))[2:]
    Q=GenPoint
    for i in range (1, len(privKeyBin)):
        Q=ECDouble(Q);
        if privKeyBin[i] == "1":
            Q=ECAdd(Q,GenPoint);
    return (Q)

publicKey = ECMultiply(GPoint,privKey)

print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
print("  'Random Password' currently set with '"+str(MAX_LEN)+"' characters:")
print()
print ("  "+password[0:128])
print ("  "+password[128:256])
print ("  "+password[256:384])
print ("  "+password[384:512])
print ("  "+password[512:640])
print ("  "+password[640:768])
print ("  "+password[768:896])
print ("  "+password[896:1024])
print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
print ("  'Private Key' derived from Hashed 'Random Password' (64 characters hexadecimal [0-9A-F], hashed by SHA3-256):")
print()
print ("  "+str(hex(privKey)[2:]).zfill(32).upper())
print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
print ("  'Public Key' derived from 'Private Key' using 'secp256k1 elliptic curve' (uncompressed, 130 characters hexadecimal [0-9A-F])")
print ("  [prefix = '04'] + [32 bytes of X coordinate] + [32 bytes of Y coordinate]:")
print()
print ("  "+"04"+str(hex(publicKey[0])[2:]).zfill(64).upper()+str(hex(publicKey[1])[2:]).zfill(64).upper())
print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
if publicKey[1] % 2 == 1: # If the Y coordinate of the Public Key is odd.
    prefix = "'03'"
else: # If the Y coordinate of the Public Key is even.
    prefix = "'02'"
print ("  'Public Key' derived from 'Private Key' using 'secp256k1 elliptic curve' (compressed, 66 characters hexadecimal [0-9A-F])")
print ("  [prefix = " + prefix + "] + [32 bytes of X coordinate]:")
print()
if publicKey[1] % 2 == 1: # If the Y coordinate of the Public Key is odd.
    print ("  "+"03"+str(hex(publicKey[0])[2:]).zfill(64).upper())
else: # If the Y coordinate of the Public Key is even.
    print ("  "+"02"+str(hex(publicKey[0])[2:]).zfill(64).upper())
print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
```

**Comment by gtmadureira** [comment]
https://github.com/gtmadureira/bitcoin_address-generator/blob/main/app_python/privkey_to_pubkey/secp256k1.py

# CODE FOR PYTHON 3:
```txt
# Super simple Elliptic Curve Presentation.
# For educational purposes only. Works in Python 3.
# Source: https://github.com/gtmadureira/bitcoin_address-generator/blob/main/app_python/privkey_to_pubkey/secp256k1.py

import random
import array
import hashlib
import os
import sys

# Checking the type of Operating System.
if sys.platform == "linux" or sys.platform == "linux2" or sys.platform == "darwin":
    def clear(): os.system('clear') # On Linux/OS X System
elif sys.platform == "win32":
    def clear(): os.system('cls') # On Windows System

clear()

# Maximum length of password needed.
# This can be changed to suit your password length.
MAX_LEN = 1024

# Declare arrays of the character that we need in out password.
# Represented as chars to enable easy string concatenation.
DIGITS = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

LOCASE_CHARACTERS = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
					 'i', 'j', 'k', 'm', 'n', 'o', 'p', 'q',
					 'r', 's', 't', 'u', 'v', 'w', 'x', 'y',
					 'z']

UPCASE_CHARACTERS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
					 'I', 'J', 'K', 'M', 'N', 'O', 'p', 'Q',
					 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y',
					 'Z']

SYMBOLS = [' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*',
           '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?',
           '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']

# Combines all the character arrays above to form one array.
COMBINED_LIST = DIGITS + UPCASE_CHARACTERS + LOCASE_CHARACTERS + SYMBOLS

# Randomly select at least one character from each character set above.
rand_digit = random.choice(DIGITS)
rand_upper = random.choice(UPCASE_CHARACTERS)
rand_lower = random.choice(LOCASE_CHARACTERS)
rand_symbol = random.choice(SYMBOLS)

# Combine the character randomly selected above
# at this stage, the password contains only 4 characters but
# we want a 12-character password.
temp_pass = rand_digit + rand_upper + rand_lower + rand_symbol

# Now that we are sure we have at least one character from each
# set of characters, we fill the rest of
# the password length by selecting randomly from the combined
# list of character above.
for x in range(MAX_LEN - 4):
	temp_pass = temp_pass + random.choice(COMBINED_LIST)

	# Convert temporary password into array and shuffle to
	# prevent it from having a consistent pattern
	# where the beginning of the password is predictable.
	temp_pass_list = array.array('u', temp_pass)
	random.shuffle(temp_pass_list)

# Traverse the temporary password array and append the chars
# to form the password.
password = ""
for x in temp_pass_list:
		password = password + x

# Hashing password with SHA3-256 algorithm.
hash = hashlib.sha3_256()
hash.update(password.encode())

privKeyStr = "0x"+hash.hexdigest() # Random Private Key at hex_string.
privKey = int(privKeyStr, 16) # Random Private Key at hex_value.

# secp256k1 domain parameters.
Pcurve = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F # The proven prime.
Acurve = 0x0000000000000000000000000000000000000000000000000000000000000000 # These two defines the elliptic curve. y^2 = x^3 + int(Acurve) * x + int(Bcurve).
Bcurve = 0x0000000000000000000000000000000000000000000000000000000000000007
Gx = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
Gy = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8
GPoint = (int(Gx),int(Gy)) # This is our generator point.
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141 # Number of points in the field.

def modinv(a, b = int(Pcurve)): #Extended Euclidean Algorithm/'division' in elliptic curves.
    lm, hm = 1,0
    low, high = a%b,b
    while low > 1:
        ratio = high//low
        nm, new = hm-lm*ratio, high-low*ratio
        lm, low, hm, high = nm, new, lm, low
    return lm % b

def ECAdd(a,b): # Point Addition, invented for EC.
    LambdaAdd = ((b[1] - a[1]) * modinv(b[0] - a[0],int(Pcurve))) % int(Pcurve)
    x = (LambdaAdd * LambdaAdd - a[0] - b[0]) % int(Pcurve)
    y = (LambdaAdd * (a[0] - x) - a[1]) % int(Pcurve)
    return (x,y)

def ECDouble(a): # Point Doubling, invented for EC.
    LamdaDouble = ((3 * a[0] * a[0] + int(Acurve)) * modinv((2 * a[1]), int(Pcurve))) % int(Pcurve)
    x = (LamdaDouble * LamdaDouble - 2 * a[0]) % int(Pcurve)
    y = (LamdaDouble * (a[0] - x) - a[1]) % int(Pcurve)
    return (x,y)

def ECMultiply(GenPoint,privKeyHex): # Doubling & Addition. Not true multiplication.
    if privKeyHex == 0 or privKeyHex >= N: raise Exception("Invalid Private Key")
    privKeyBin = str(bin(privKeyHex))[2:]
    Q=GenPoint
    for i in range (1, len(privKeyBin)):
        Q=ECDouble(Q);
        if privKeyBin[i] == "1":
            Q=ECAdd(Q,GenPoint);
    return (Q)

publicKey = ECMultiply(GPoint,privKey)

print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
print("  'Random Password' currently set with '"+str(MAX_LEN)+"' characters:")
print()
print ("  "+password[0:128])
print ("  "+password[128:256])
print ("  "+password[256:384])
print ("  "+password[384:512])
print ("  "+password[512:640])
print ("  "+password[640:768])
print ("  "+password[768:896])
print ("  "+password[896:1024])
print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
print ("  'Private Key' derived from Hashed 'Random Password' (64 characters hexadecimal [0-9A-F], hashed by SHA3-256):")
print()
print ("  "+str(hex(privKey)[2:]).zfill(32).upper())
print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
print ("  'Public Key' derived from 'Private Key' using 'secp256k1 elliptic curve' (uncompressed, 130 characters hexadecimal [0-9A-F])")
print ("  [prefix = '04'] + [32 bytes of X coordinate] + [32 bytes of Y coordinate]:")
print()
print ("  "+"04"+str(hex(publicKey[0])[2:]).zfill(64).upper()+str(hex(publicKey[1])[2:]).zfill(64).upper())
print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
if publicKey[1] % 2 == 1: # If the Y coordinate of the Public Key is odd.
    prefix = "'03'"
else: # If the Y coordinate of the Public Key is even.
    prefix = "'02'"
print ("  'Public Key' derived from 'Private Key' using 'secp256k1 elliptic curve' (compressed, 66 characters hexadecimal [0-9A-F])")
print ("  [prefix = " + prefix + "] + [32 bytes of X coordinate]:")
print()
if publicKey[1] % 2 == 1: # If the Y coordinate of the Public Key is odd.
    print ("  "+"03"+str(hex(publicKey[0])[2:]).zfill(64).upper())
else: # If the Y coordinate of the Public Key is even.
    print ("  "+"02"+str(hex(publicKey[0])[2:]).zfill(64).upper())
print()
print("--------------------------------------------------------------------------------------------------------------------------------------------")
print()
```

**Comment by gtmadureira** [comment]
### CODE FOR PYTHON 3.6.13 OR HIGHER (UPDATED) :

https://github.com/gtmadureira/bitcoin_address-generator/tree/main/app_python/ecc_tests/secp256k1

**Comment by NewbieOubie2017** [comment]
Thank you so very much Gustave!  It works nicely once the indent at line 66 and 67 is adjusted.


________________________________

**Comment by gtmadureira** [comment]
If I use the same source code, but for curve 25519, where the cofactor is "h = 8". How would I implement this "cofactor" in the source code? 
Just for testing and learning.
